name: eLupiHaler website #Author ghanashyam
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Login and deploy node app
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST_PROD }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_KEY_PROD }}
        port: ${{ secrets.SSH_PORT }}
        proxy_host: ${{ secrets.SSH_HOST }}
        proxy_username: ${{ secrets.SSH_USERNAME }}
        proxy_password: ${{ secrets.SSH_KEY }}
        proxy_port: ${{ secrets.SSH_PORT }}
        script: |
          cd /usr/local/share/applications/smart_DPI_website
          sudo git reset --hard
          sudo git pull  https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/wynd-custom-projects/smart_DPI_website.git
